-- Cards Against Humanity - Autism Community Edition
-- A family-friendly deck celebrating autism culture and experiences
-- 90 Black Cards + 510 White Cards

-- First, create the new deck
INSERT INTO public.decks (name, type) VALUES
('Cards Against Humanity - Autism Edition', 'clean');

-- ============================================
-- BLACK CARDS (90 Prompts)
-- ============================================
INSERT INTO public.black_cards (deck_id, text, pick) VALUES
-- Special Interests
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My special interest this month is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I could talk for 3 hours straight about _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Warning: Do not ask me about _____ unless you have 4 hours free.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My Wikipedia rabbit hole last night started with cats and ended with _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The best thing about having a special interest in _____ is _____.', 2),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I''ve memorized every fact about _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My collection of _____ has officially taken over my room.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I organized my entire bookshelf by _____.', 1),

-- Sensory Experiences
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The worst texture in the world is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I would pay good money to never hear _____ again.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My noise-canceling headphones saved me from _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The most satisfying sensory experience is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'This weighted blanket feels like _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Fluorescent lights are _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The tag on this shirt feels like _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I cut all the tags off my clothes because of _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My favorite stim is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Nothing beats the feeling of _____.', 1),

-- Social Situations
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'When someone says "we should hang out sometime," I think _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Small talk is basically _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I was being sarcastic, but everyone thought I meant _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The worst part of parties is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Why say "how are you" when you could say "_____"?', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I took the phrase "break a leg" literally and _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Eye contact feels like _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My face says _____, but inside I''m feeling _____.', 2),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The unwritten rule I accidentally broke was _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'They said "be yourself" so I _____.', 1),

-- Routines and Schedules
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My morning routine was ruined by _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'If _____ isn''t in its proper place, I will not survive.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The schedule says _____, so that''s what we''re doing.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Change of plans? More like _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My comfort meal is _____ for the 47th day in a row.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I''ve watched the same show _____ times because it''s comforting.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Unexpected visitors are basically _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My daily planner is organized by _____.', 1),

-- Communication
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I said exactly what I meant, and somehow that was _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The best thing about texting is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Phone calls are basically _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I spent 20 minutes crafting the perfect response: "_____."', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'What neurotypicals call "blunt," I call _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I didn''t realize "how are you" wasn''t a real question until _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My therapist says I should work on _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I communicate best through _____.', 1),

-- Executive Function
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I meant to do _____ but instead I _____.', 2),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My to-do list includes _____ from three months ago.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The hardest part of starting a task is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I hyperfocused on _____ for 8 hours and forgot to eat.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Object permanence? More like _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I put the milk in the _____ again.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Time blindness led me to _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I set 47 alarms for _____.', 1),

-- Autism Life
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Getting diagnosed felt like _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The autism community taught me _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Masking all day is like _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'After a long day of peopling, I need _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My meltdown was triggered by _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The best thing about being autistic is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Autism isn''t a tragedy. _____ is a tragedy.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I''m not "high-functioning." I''m _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Before I knew I was autistic, I thought I was just _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My autistic superpower is _____.', 1),

-- Humor and Observations
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Neurotypicals are weird because they _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I have strong opinions about _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My brain at 3am is thinking about _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'According to my research, _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I corrected someone about _____ and now they won''t talk to me.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The thing I notice that nobody else does is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), '"It''s not that deep" they said, while I was thinking about _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I have a system for _____ that nobody else understands.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My pattern recognition skills revealed _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The most logical solution is clearly _____.', 1),

-- Mixed/Fun
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'In an ideal world, everyone would understand _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My comfort character is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I made a spreadsheet about _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The internet taught me that _____ is actually autism.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My "weird kid" energy is actually _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The best accommodation I ever got was _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I''ve been called "too much" because of _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My happy stim is triggered by _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The perfect Friday night is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'If autism was a superpower, mine would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The thing I wish neurotypicals understood is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'I found my people when _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'My sensory kit includes _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The moment I realized I was autistic was when _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), '_____ is proof that autistic joy exists.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Step 1: _____. Step 2: _____. Step 3: Finally leave the house.', 2);

-- ============================================
-- WHITE CARDS (510 Answers)
-- ============================================
INSERT INTO public.white_cards (deck_id, text) VALUES
-- Special Interests (common ones)
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Trains'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Dinosaurs'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Space and astronomy'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Video games'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Minecraft'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Pokémon'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Star Wars'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Star Trek'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Doctor Who'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Lord of the Rings'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Harry Potter'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Marine biology'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Sharks'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Whales'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Octopuses'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Bugs and insects'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Birds'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Cats'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Dogs'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Horses'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Reptiles'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Music theory'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'A very specific historical period'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'World War II tanks'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Medieval castles'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Ancient Egypt'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The Roman Empire'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Vikings'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Pirates'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Cryptids and monsters'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'True crime'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Weather patterns'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Tornadoes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Volcanoes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Earthquakes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Maps and geography'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Flags of the world'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Languages'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Etymology'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Typography and fonts'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Coding and programming'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Mathematics'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Physics'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Chemistry'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Periodic table elements'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Lego'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Building and engineering'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Rubik''s cubes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Puzzles'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Board games'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Card games'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Dungeons & Dragons'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Fantasy worlds'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Worldbuilding'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Fan fiction'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Anime'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Manga'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'K-pop'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'A specific band'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Musical instruments'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Art history'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Drawing and illustration'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Knitting and crochet'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Sewing and costumes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Cooking and baking'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Plant care'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Gardening'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Collecting things'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Organizing things'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Making lists'),

-- Sensory Related
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The perfect texture'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The wrong texture'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Soft blankets'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Weighted blankets'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Noise-canceling headphones'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Earplugs'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Sunglasses indoors'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Fluorescent lights'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'LED lights'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The hum of electronics'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Clock ticking'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Loud chewing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Unexpected loud noises'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Background music in stores'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Multiple conversations at once'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'That specific fabric that feels wrong'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Tags on clothes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Seams on socks'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Itchy sweaters'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Wet sleeves'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Cotton balls'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Styrofoam'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Velvet'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Corduroy'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Sand'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Slime'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Play-doh'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Kinetic sand'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Bubble wrap'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Popping bubble wrap'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The smell of rain'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'That one specific smell'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Strong perfume'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Food touching other food'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Mixed textures in food'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The wrong temperature food'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Satisfying crunchy sounds'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'White noise'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Brown noise'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Rain sounds'),

-- Stims
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Hand flapping'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Rocking back and forth'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Spinning'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Bouncing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Pacing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Clicking pens'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Fidget spinners'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Fidget cubes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Stim toys'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Chewing on things'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Chewelry'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Hair twirling'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Skin picking'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Humming'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Echolalia'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Repeating favorite phrases'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Movie quotes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Scripting conversations'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Tapping rhythms'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Leg bouncing'),

-- Social/Communication
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Being brutally honest'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Taking things literally'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Missing sarcasm'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Over-explaining everything'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Infodumping'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Not knowing when to stop talking'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Going completely silent'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Forgetting to respond'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Responding three days later'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Overthinking a text'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The perfect comeback, two hours late'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Accidentally being rude'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Accidentally being too honest'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Saying the wrong thing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Awkward silence'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Not knowing how to end a conversation'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Walking away mid-conversation'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Avoiding phone calls'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Letting calls go to voicemail'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Texting instead of calling'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Email anxiety'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Rehearsing conversations'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Planning what to say'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Social scripts'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Masking'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Unmasking'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The exhaustion of masking'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Finally being yourself'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Finding your people'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Parallel play'),

-- Routines and Organization
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'A very specific routine'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The same breakfast every day'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Safe foods'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Eating the same meal for weeks'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Chicken nuggets'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Plain pasta'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Pizza without toppings'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Food that doesn''t touch'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Color-coded organization'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Alphabetical order'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Everything in its place'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Detailed schedules'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Google Calendar'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Setting 50 reminders'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Arriving exactly on time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Arriving 30 minutes early'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Needing exact times'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), '"Soon" is not a time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Hating last-minute changes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Needing advance notice'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Planning everything'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Having a backup plan'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Researching before going somewhere new'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Checking the menu beforehand'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Street View reconnaissance'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Sitting in the same spot'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Taking the same route'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Rewatching the same show'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Rereading the same book'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Comfort media'),

-- Executive Function
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Hyperfocus'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Losing track of time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Time blindness'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Forgetting to eat'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Forgetting to drink water'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Forgetting basic needs'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Starting a new project'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Never finishing projects'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Having 47 unfinished projects'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Procrastination'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Task paralysis'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Not knowing where to start'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The Doom pile'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Out of sight, out of mind'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Object permanence issues'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Putting things in the wrong place'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Finding the remote in the fridge'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Decision fatigue'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Too many choices'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Analysis paralysis'),

-- Feelings and Experiences
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Autistic burnout'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Needing recovery time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The social battery'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Recharging alone'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Meltdowns'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Shutdowns'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Sensory overload'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Overstimulation'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Understimulation'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Emotional dysregulation'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Big feelings'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Alexithymia'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Not knowing what I''m feeling'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Delayed emotional processing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Rejection sensitivity'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Intense empathy'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Feeling everything deeply'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Justice sensitivity'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Strong sense of fairness'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Autistic joy'),

-- Life Experiences
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Late diagnosis'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Self-diagnosis'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The autism assessment'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Finally understanding yourself'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Realizing you''re autistic'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Reading about autism and crying'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Finding the autism community'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Actually Autistic'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Neurodivergent pride'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The infinity symbol'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Gold instead of blue'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Autism acceptance'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Nothing about us without us'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Disability pride'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Asking for accommodations'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Noise-canceling everything'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Stimming in public'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Being unapologetically autistic'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Autistic culture'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Autistic humor'),

-- Observations and Quirks
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Pattern recognition'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Noticing details others miss'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Remembering random facts'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Having an excellent memory'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Remembering exact conversations'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Encyclopedic knowledge'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Being the expert'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Correcting people'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), '"Well, actually..."'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Being technically correct'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The best kind of correct'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Attention to detail'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Finding errors others miss'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Quality control'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Spotting inconsistencies'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Being a walking Wikipedia'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Hyperlexia'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Reading really fast'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Advanced vocabulary'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Talking like a professor'),

-- Technology and Media
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'AAC'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Text-to-speech'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Closed captions'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Subtitles for everything'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Watching at 2x speed'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Needing to see what happens next'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Looking up spoilers'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Reading the plot summary first'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Having multiple screens'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Background TV'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The same video on repeat'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Wikipedia deep dives'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Opening 100 browser tabs'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Research mode'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Spreadsheets'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Making databases'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Organizing digital files'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Having a system'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Apps for everything'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Accessibility features'),

-- Social Situations
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Small talk'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Hating small talk'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Going straight to deep topics'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Intense conversations'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Special interest bonding'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Info-dumping to friends'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Finding other autistics'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The autistic nod of recognition'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Being weird together'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Alone together'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Online friendships'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Discord servers'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Neurodivergent spaces'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Safe people'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Low-demand friendships'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'No-judgment zones'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Just existing together'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Comfortable silence'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Not having to mask'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Being understood'),

-- Humor
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Puns'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Wordplay'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Dry humor'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Deadpan delivery'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Inside jokes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Obscure references'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Running jokes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Quoting movies'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Memes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Autism memes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Self-deprecating humor'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Absurdist humor'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Very specific jokes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Laughing at your own joke'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Explaining the joke'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Not getting the joke'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Getting the joke 3 days later'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Laughing at nothing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Stimming from laughing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Uncontrollable giggling'),

-- Objects and Things
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Comfort objects'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Stuffed animals'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'That one specific plushie'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Emotional support water bottle'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The perfect hoodie'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Wearing the same outfit'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Owning 5 of the same shirt'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Soft clothes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Compression clothing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Specific brands'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Specific foods'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Specific everything'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Backups of favorite things'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Hoarding supplies'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Collections'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Having too many of something'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The perfect pen'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The right notebook'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Sensory toys'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Stim jewelry'),

-- Actions and Behaviors
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Organizing everything'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Reorganizing everything'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Researching obsessively'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Learning everything about something'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Becoming an expert overnight'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Going down rabbit holes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Fact-checking everything'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Double-checking everything'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Overthinking'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Underthinking'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Thinking in pictures'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Thinking in patterns'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Systems thinking'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Seeing the big picture'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Missing the big picture'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Getting lost in details'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Tunnel vision'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Laser focus'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Being completely absorbed'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Zone mode'),

-- More Experiences
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Stimming with joy'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Flappy hands'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Happy bouncing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Excitement overload'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Anticipation'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The wait is the hardest part'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Counting down days'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Special occasions'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Birthday traditions'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Holiday routines'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Comfort activities'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Relaxation time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Decompression'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Quiet time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Alone time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Peaceful solitude'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Being in nature'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Animals understanding you'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Pets as therapy'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The understanding cat'),

-- Random Fun
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Knowing random facts'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Trivia night domination'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Being weirdly good at something'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Hidden talents'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Unexpected skills'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Niche expertise'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Being the go-to person'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Having all the answers'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Actually reading the manual'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Following instructions exactly'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Rules are rules'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Fair is fair'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Logical solutions'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Efficient systems'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The obvious answer'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Thinking outside the box'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'What box?'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'A different perspective'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Unique problem-solving'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Creative solutions'),

-- Final Mix
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The autism spectrum'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Spiky profiles'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Different, not less'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Neurodiversity'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Brain differences'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Neurotype'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'The autistic brain'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Wired differently'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'A beautiful mind'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Being authentic'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Self-acceptance'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Embracing differences'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Finding your tribe'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Community'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Understanding'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Acceptance'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Belonging'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Home'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Peace'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Autism Edition'), 'Joy');

-- Verify the card counts
SELECT 
  d.name as deck_name,
  (SELECT COUNT(*) FROM black_cards WHERE deck_id = d.id) as black_cards,
  (SELECT COUNT(*) FROM white_cards WHERE deck_id = d.id) as white_cards
FROM decks d
WHERE d.name = 'Cards Against Humanity - Autism Edition';
