-- Cards Against Humanity - Children's Edition
-- A fun, family-friendly deck perfect for kids
-- 90 Black Cards + 510 White Cards

-- Create the new deck
INSERT INTO public.decks (name, type) VALUES
('Cards Against Humanity - Kids Edition', 'clean');

-- ============================================
-- BLACK CARDS (90 Prompts)
-- ============================================
INSERT INTO public.black_cards (deck_id, text, pick) VALUES

-- Fun Activities
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite thing to do at recess is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best part of summer vacation is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'When I grow up, I want to be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite subject in school is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The coolest thing about _____ is _____.', 2),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could have any superpower, I would choose _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite thing to build with blocks is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best birthday party would have _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'I love playing with _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite game is _____.', 1),

-- Silly Scenarios
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If animals could talk, _____ would say _____.', 2),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The funniest thing I ever saw was _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I were a superhero, my sidekick would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The silliest thing to put on a pizza is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could fly, I would go to _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The weirdest pet would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I had a magic wand, I would make _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The funniest name for a robot would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could invent anything, it would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best thing to do on a rainy day is _____.', 1),

-- Food & Snacks
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite snack is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best ice cream flavor is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'For lunch, I always want _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The yuckiest food combination is _____ and _____.', 2),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite dessert is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best pizza topping is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could eat only one food forever, it would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The weirdest thing to put in a sandwich is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite breakfast is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best drink is _____.', 1),

-- Animals & Nature
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite animal is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could be any animal, I would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The coolest dinosaur is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite thing about _____ is _____.', 2),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best pet would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could talk to animals, I would ask _____ about _____.', 2),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The funniest animal sound is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite thing to do outside is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best thing about nature is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could visit any place, I would go to _____.', 1),

-- School & Learning
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best thing about school is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite book is about _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The coolest thing I learned was _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I were the teacher, I would teach _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best school subject is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite thing to draw is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The funniest thing that happened at school was _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could change one thing about school, it would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best field trip would be to _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite thing to learn about is _____.', 1),

-- Family & Friends
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best thing about my family is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite thing to do with friends is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The funniest thing my friend did was _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could have any sibling, they would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best thing about having a best friend is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite family tradition is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The coolest thing my parent does is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could give my friend anything, it would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best thing about sleepovers is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite thing to do with my family is _____.', 1),

-- Holidays & Celebrations
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best part of my birthday is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite holiday is _____ because _____.', 2),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best Halloween costume would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The coolest thing about Christmas is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite thing about holidays is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best party game is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could celebrate any day, it would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The funniest thing that happened at a party was _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best birthday gift would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite celebration is _____.', 1),

-- Imagination & Creativity
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could create my own planet, it would have _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best story I ever made up was about _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could design a video game, it would be about _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The coolest thing I can imagine is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could build anything, I would build _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best pretend game is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could write a book, it would be about _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The funniest character I can think of is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could make a movie, it would star _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best thing to pretend to be is _____.', 1),

-- Sports & Activities
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite sport is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best thing about playing _____ is _____.', 2),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could be a professional athlete, I would play _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The coolest trick I can do is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite thing to do at the park is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best game to play outside is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could win any competition, it would be for _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The funniest thing that happened during a game was _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best thing about being active is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite way to exercise is _____.', 1),

-- Technology & Media
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite video game is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best cartoon character is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could be in any TV show, it would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The coolest app would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite movie is about _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best YouTube video would be about _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could create my own TV show, it would be about _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The funniest thing I saw online was _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best thing about technology is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite thing to watch is _____.', 1),

-- Random Fun
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The silliest thing I ever did was _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could change one thing about the world, it would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best joke I know is about _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'My favorite thing to collect is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The coolest thing I own is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could have any talent, it would be _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The funniest thing that makes me laugh is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The best thing about being a kid is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'If I could do anything for a day, I would _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The most awesome thing ever is _____.', 1);

-- ============================================
-- WHITE CARDS (510 Answers)
-- ============================================
INSERT INTO public.white_cards (deck_id, text) VALUES

-- Animals
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A puppy'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A kitten'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A unicorn'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A dragon'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A dinosaur'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A penguin'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A monkey'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A dolphin'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A tiger'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A lion'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A bear'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A bunny'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A hamster'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A goldfish'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A parrot'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A turtle'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A snake'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A frog'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A butterfly'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A bee'),

-- Food & Snacks
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Pizza'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Ice cream'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Candy'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Cookies'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Cake'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Chocolate'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'French fries'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Mac and cheese'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Chicken nuggets'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Hot dogs'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Hamburgers'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Pancakes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Waffles'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Donuts'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Popcorn'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Chips'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Apples'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Bananas'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Strawberries'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Grapes'),

-- Toys & Games
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Lego'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Action figures'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Dolls'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Toy cars'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Board games'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Video games'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Puzzles'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Building blocks'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Stuffed animals'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Art supplies'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Balls'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Jump ropes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Hula hoops'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Scooters'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Bicycles'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Kites'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Bubbles'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Play-doh'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Slime'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Fidget spinners'),

-- Activities
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Playing tag'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Hide and seek'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Jumping on a trampoline'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Swimming'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Riding bikes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Playing soccer'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Playing basketball'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Drawing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Coloring'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Painting'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Singing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Dancing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Reading'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Building forts'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Playing pretend'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Making up stories'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Playing instruments'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Going to the park'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Playing at the playground'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Having a picnic'),

-- Places
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The playground'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The park'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The beach'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The zoo'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The aquarium'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The museum'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The library'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The movie theater'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The arcade'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The amusement park'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The water park'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The ice cream shop'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The toy store'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Grandma''s house'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A friend''s house'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'School'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The backyard'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The treehouse'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The clubhouse'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The fort'),

-- Characters & Heroes
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Superman'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Batman'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Wonder Woman'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Spider-Man'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A princess'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A knight'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A pirate'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A ninja'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A wizard'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A fairy'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A mermaid'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A robot'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'An astronaut'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A firefighter'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A police officer'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A doctor'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A teacher'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A chef'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A scientist'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'An explorer'),

-- School Subjects
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Math'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Science'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Reading'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Art'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Music'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Gym'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'History'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Geography'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Computer class'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Library time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Recess'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Lunch'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Field trips'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Show and tell'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Story time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Science experiments'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Art projects'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Music class'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'PE class'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Free time'),

-- Sports
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Soccer'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Basketball'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Baseball'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Football'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Tennis'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Swimming'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Gymnastics'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Dance'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Karate'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Skiing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Skateboarding'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Roller skating'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Jumping rope'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Running'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Climbing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Riding bikes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Playing catch'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Tag'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Hide and seek'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Kickball'),

-- Holidays & Celebrations
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Birthday parties'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Christmas'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Halloween'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Easter'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Thanksgiving'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Valentine''s Day'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'New Year''s'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The Fourth of July'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Hanukkah'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Diwali'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Birthday cake'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Presents'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Party games'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Balloons'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Confetti'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Party hats'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Pinatas'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Decorations'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Music and dancing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Friends'),

-- Colors
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Red'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Blue'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Green'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Yellow'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Orange'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Purple'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Pink'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Rainbow'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Sparkly'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Glowing'),

-- Weather & Nature
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Sunshine'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Rainbows'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Rain'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Snow'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Clouds'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Stars'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The moon'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'The sun'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Flowers'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Trees'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Mountains'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Oceans'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Rivers'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Forests'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Deserts'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Islands'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Caves'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Waterfalls'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Volcanoes'),

-- Technology & Media
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Minecraft'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Roblox'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Pokémon'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Super Mario'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Sonic the Hedgehog'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Disney movies'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Cartoons'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Animated movies'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Superhero movies'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'YouTube videos'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Tablets'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Computers'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Smartphones'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'TV shows'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Movies'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Music'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Podcasts'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Apps'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Games'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Streaming'),

-- Family & Relationships
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Mom'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Dad'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Grandma'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Grandpa'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Siblings'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Cousins'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Aunts and uncles'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Best friends'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Classmates'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Teachers'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Neighbors'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Pets'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Babysitters'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Coaches'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Team members'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Pen pals'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Study buddies'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Playmates'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Adventure partners'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Imaginary friends'),

-- Emotions & Feelings
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Happiness'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Excitement'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Joy'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Laughter'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Fun'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Adventure'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Wonder'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Curiosity'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Pride'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Love'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Friendship'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Kindness'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Bravery'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Creativity'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Imagination'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Surprise'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Amazement'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Giggles'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Smiles'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Hugs'),

-- Superpowers & Magic
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Flying'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Invisibility'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Super strength'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Super speed'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Teleportation'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Mind reading'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Shape-shifting'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Time travel'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Magic powers'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'X-ray vision'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Ice powers'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Fire powers'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Water powers'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Lightning powers'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Healing powers'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Telekinesis'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Super hearing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Super jumping'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Force fields'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Magic wands'),

-- Vehicles & Transportation
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Cars'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Trucks'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Buses'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Trains'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Airplanes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Helicopters'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Rockets'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Spaceships'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Boats'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Submarines'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Bicycles'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Scooters'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Skateboards'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Roller skates'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Hoverboards'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Hot air balloons'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Race cars'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Monster trucks'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Motorcycles'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Go-karts'),

-- Silly & Fun
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Silly faces'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Funny jokes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Dancing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Singing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Making funny sounds'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Telling stories'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Playing pranks'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Being silly'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Laughing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Giggling'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Making up songs'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Doing impressions'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Telling knock-knock jokes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Making funny faces'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Pretending to be animals'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Acting silly'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Being goofy'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Making people laugh'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Having fun'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Being creative'),

-- Time & Seasons
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Morning'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Afternoon'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Evening'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Nighttime'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Spring'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Summer'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Fall'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Winter'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Weekends'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Summer vacation'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Winter break'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Spring break'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Holidays'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Birthdays'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Special days'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Today'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Tomorrow'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Yesterday'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Right now'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Forever'),

-- Numbers & Quantities
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'One'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Two'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Three'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A hundred'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A thousand'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A million'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'A billion'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Infinite'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Too many to count'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Just the right amount'),

-- Sizes & Descriptions
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Tiny'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Small'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Big'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Huge'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Giant'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Enormous'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Super-sized'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Mini'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Jumbo'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Gigantic'),

-- More Fun Things
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Adventures'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Treasure hunts'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Scavenger hunts'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Mysteries'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Secrets'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Surprises'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Discoveries'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Explorations'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Quests'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Journeys'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Missions'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Challenges'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Achievements'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Victories'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Celebrations'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Triumphs'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Success'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Winning'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Being awesome'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Kids Edition'), 'Having the best day ever');

-- Verify the card counts
SELECT 
  d.name as deck_name,
  (SELECT COUNT(*) FROM black_cards WHERE deck_id = d.id) as black_cards,
  (SELECT COUNT(*) FROM white_cards WHERE deck_id = d.id) as white_cards
FROM decks d
WHERE d.name = 'Cards Against Humanity - Kids Edition';
