-- Cards Against Humanity - Life Skills & Social Navigator Edition
-- Family-friendly deck focusing on:
-- - Literal language understanding
-- - Following directions
-- - Multi-step processing
-- - Social etiquette
-- - Critical thinking
-- - Situational awareness (danger vs adventure)
-- - Fun scenarios and identifying bad behaviors

-- Create the new deck
INSERT INTO public.decks (name, type) VALUES
('Cards Against Humanity - Life Skills Edition', 'clean');

-- ============================================
-- BLACK CARDS (90 Prompts)
-- ============================================
INSERT INTO public.black_cards (deck_id, text, pick) VALUES

-- Following Directions / Literal Language
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The recipe said "beat the eggs" so I _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'My teacher said "hit the books" and I _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'When they said "break a leg," I thought they meant _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The sign said "Watch your step" so I _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"Keep an eye on the baby" meant I should _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Step 1: _____. Step 2: _____. Step 3: Success!', 2),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The instructions said "fold in the cheese" so I literally _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'When Mom said "hop to it," I _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The fire drill instructions were: Stop. _____. Roll.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The GPS said "turn right" but what I heard was _____.', 1),

-- Social Etiquette Scenarios
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'At a fancy dinner, the WRONG thing to do is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'When meeting someone new, you should NOT _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The polite response when someone sneezes is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'When you accidentally bump into someone, the best response is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'At a movie theater, the rudest thing you can do is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'When someone is talking, you should wait until _____ before speaking.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The appropriate response to receiving a gift you don''t like is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'In an elevator with strangers, the socially acceptable thing to do is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'When your friend is sad, the best thing to say is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'At a job interview, you should definitely NOT mention _____.', 1),

-- Danger Awareness
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'If you smell smoke, the FIRST thing you should do is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A stranger offers you candy. The correct response is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'You''re home alone and someone knocks. You should _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'If your friend dares you to do something dangerous, you should _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The reason you shouldn''t run with scissors is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Before crossing the street, you should always _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'If you see something suspicious, you should _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'When lost in a public place, the BEST person to ask for help is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A red flag that something might be a scam is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The emergency number to call is _____.', 1),

-- Critical Thinking
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Before believing something online, you should check _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The problem with "everyone is doing it" as an argument is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'When someone says "trust me," you should _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The difference between a fact and an opinion is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'If something sounds too good to be true, it probably is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Before making a big decision, you should _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The first question to ask when solving a problem is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'When two friends are fighting, the best thing to do is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'You find $20 on the ground. The right thing to do is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'If Plan A doesn''t work, you should _____.', 1),

-- Multi-Step Processing
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Making a sandwich: First bread, then _____, then _____.', 2),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Getting ready for school: Wake up, _____, then _____.', 2),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Before leaving the house, check for: keys, phone, and _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The morning routine goes: alarm, _____, breakfast.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'To bake cookies, first preheat, then _____, then bake.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Laundry steps: sort, wash, dry, then _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'After using the bathroom: flush, _____, dry hands.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Getting a job requires: application, interview, then _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Before bed: brush teeth, _____, then sleep.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Cooking pasta: boil water, add pasta, _____, serve.', 1),

-- Adventure Scenarios
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'You find a mysterious map. Your next step is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The best part of going camping is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'You discover a hidden door in your house. You should _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'On a road trip, the most important thing to bring is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'You meet a talking animal. Your first question is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The secret to a successful adventure is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'If I could explore anywhere, I would go to _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The treasure at the end of the rainbow is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A good adventure buddy always brings _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'You find a time machine. You travel to _____.', 1),

-- Identifying Bad Behaviors
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A bad friend is someone who _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The problem with lying is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Taking something without asking is called _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The consequence of not following rules is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Bullying is wrong because _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Being late all the time shows _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Not cleaning up after yourself means _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Interrupting people is rude because _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Cheating is bad because _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The problem with blaming others is _____.', 1),

-- Situational Awareness
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'You notice your friend looks sad. You should _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The room is getting very quiet. This probably means _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Everyone starts leaving. You should probably _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Your parent gives you "the look." This means _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The dog is growling. You should _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Dark clouds are gathering. You should _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Someone is following you. The safe thing to do is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Your stomach is growling. This means _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'People are whispering and looking at you. You should _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The traffic light is yellow. You should _____.', 1),

-- Problem Solving
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'You forgot your homework. The best solution is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Your phone battery is dying. You should _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'You accidentally broke something. The honest thing to do is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'You''re running late. The first thing to do is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'You can''t find your keys. A good strategy is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Someone is being mean online. The best response is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'You don''t understand the instructions. You should _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'You made a mistake. The mature response is _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Two friends want to hang out at the same time. You should _____.', 1),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'You''re feeling overwhelmed. A helpful strategy is _____.', 1);

-- ============================================
-- WHITE CARDS (510 Answers)
-- ============================================
INSERT INTO public.white_cards (deck_id, text) VALUES

-- Correct/Good Responses
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Saying "please" and "thank you"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Waiting your turn'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Listening carefully'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Asking for help'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Taking a deep breath'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Thinking before speaking'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Being patient'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Using your indoor voice'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Making eye contact'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Saying sorry'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Forgiving others'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Sharing with friends'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Being kind'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Telling the truth'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Keeping promises'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Respecting boundaries'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Using good manners'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Following the rules'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Being on time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Cleaning up after yourself'),

-- Literal Interpretations (Funny)
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Actually breaking a leg'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Punching the eggs with my fist'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Staring at my feet while walking'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Literally holding my tongue'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Folding the cheese like a napkin'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Actually hopping like a bunny'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Putting my eyeball on the baby'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Physically hitting the books'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Standing perfectly still for an hour'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Taking my shoes off and shaking them'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Literally biting my tongue'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Turning exactly 90 degrees'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Getting a ladder to "reach for the stars"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Looking for cats and dogs falling from the sky'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Putting on a thinking cap (an actual cap)'),

-- Bad Behaviors (What NOT to do)
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Yelling really loud'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Ignoring everyone'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Running away screaming'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Blaming someone else'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Having a tantrum'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Refusing to listen'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Rolling your eyes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Slamming the door'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Giving up immediately'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Making excuses'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Talking back'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Being mean on purpose'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Whining and complaining'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Not paying attention'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Pushing and shoving'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Interrupting constantly'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Taking things without asking'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Lying about it'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Pretending it didn''t happen'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Texting during dinner'),

-- Safety Responses
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Telling a trusted adult'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Calling 911'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Getting to a safe place'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Looking both ways'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Staying calm'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Finding an exit'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Not opening the door'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Saying no and walking away'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Staying with the group'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Using the buddy system'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Checking with a parent first'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Memorizing your address'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Stop, drop, and roll'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Finding a police officer'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Going to a store clerk'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Not talking to strangers'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Using crosswalks'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Wearing a seatbelt'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Looking up from your phone'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Following the evacuation route'),

-- Social Responses
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A firm handshake'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A friendly smile'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Saying "excuse me"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Introducing yourself'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Asking how their day is going'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Complimenting something specific'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Remembering their name'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Active listening'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Nodding to show you understand'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Asking follow-up questions'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Giving them space'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Respecting their opinion'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Agreeing to disagree'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Saying "bless you"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Holding the door open'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Offering to help'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Writing a thank-you note'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'RSVP-ing on time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Bringing a gift'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Showing up when you said you would'),

-- Steps and Sequences
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Getting dressed'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Brushing your teeth'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Taking a shower'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Making your bed'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Eating breakfast'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Packing your bag'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Double-checking everything'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Setting an alarm'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Making a list'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Checking off tasks'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Putting things in order'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Following the recipe'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Reading the instructions'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'One step at a time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Starting at the beginning'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Folding the laundry'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Washing your hands'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Putting things away'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Turning off the lights'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Locking the door'),

-- Critical Thinking
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Asking questions'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Checking multiple sources'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Thinking about consequences'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Considering other perspectives'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Weighing the pros and cons'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Looking at the evidence'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Trusting your gut'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Sleeping on it'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Getting a second opinion'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Doing your research'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Reading the fine print'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Using common sense'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Learning from mistakes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Trying a different approach'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Breaking it into smaller parts'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Looking at the big picture'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Fact versus opinion'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Cause and effect'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Thinking ahead'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Having a backup plan'),

-- Adventure/Fun Responses
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A treasure map'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A secret passage'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Making new friends'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Exploring somewhere new'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Building a fort'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Going on a quest'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Solving a mystery'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Finding hidden treasure'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Climbing a mountain'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Sailing the seas'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Flying through the clouds'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Discovering a new species'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Meeting a friendly dragon'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Finding a magic portal'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Winning the championship'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Making the team'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Getting an A on the test'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Making someone laugh'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Having the best day ever'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Eating ice cream'),

-- Emotions and Feelings
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling happy'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling sad'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling angry'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling scared'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling excited'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling nervous'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling proud'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling embarrassed'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling confused'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling frustrated'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling lonely'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling grateful'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling loved'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling overwhelmed'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling calm'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling worried'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling disappointed'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling hopeful'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling curious'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling brave'),

-- Places
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The library'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The grocery store'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The doctor''s office'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'School'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Home'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The park'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The mall'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A restaurant'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The movies'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A friend''s house'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The beach'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The mountains'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A museum'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'An amusement park'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The zoo'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Summer camp'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Grandma''s house'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The post office'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The bank'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A birthday party'),

-- People
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A police officer'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A firefighter'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A teacher'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A parent'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A doctor'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A friend'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A librarian'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A coach'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A neighbor'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A bus driver'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The principal'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A crossing guard'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A lifeguard'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A security guard'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Your best friend'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A helpful stranger'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Store employees'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Someone in a uniform'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A trusted adult'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Someone you just met'),

-- Objects/Things
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A phone'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Your wallet'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Your keys'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A flashlight'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A first aid kit'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Snacks'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Water'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A map'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A compass'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Sunscreen'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'An umbrella'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A jacket'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Comfortable shoes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A notebook'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A pen'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Your homework'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Your lunch'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Medicine'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Your ID'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Emergency contacts'),

-- Problem Solutions
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Starting over'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Trying again'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Taking a break'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Asking someone who knows'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Looking it up'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Writing it down'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Making a plan'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Staying positive'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Being flexible'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Compromising'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Finding middle ground'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Using a timer'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Breaking it into steps'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Setting goals'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Celebrating small wins'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Not giving up'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Practicing more'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Getting organized'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Prioritizing what''s important'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Saying "I''ll figure it out"'),

-- Consequences
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Getting in trouble'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Losing trust'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Missing out'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Having to redo it'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Feeling guilty'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Hurting someone''s feelings'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Making things worse'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Learning a lesson'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Getting grounded'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Losing privileges'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Having to apologize'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Cleaning up the mess'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Losing a friend'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Being late'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Missing dinner'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Extra homework'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Detention'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A serious talk'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Natural consequences'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A timeout'),

-- Silly/Funny Answers
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Doing a silly dance'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Making weird noises'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Spinning in circles'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Hiding under the bed'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Pretending to be a statue'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Talking to yourself'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Walking backwards'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Speaking in a funny voice'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Wearing your shoes on the wrong feet'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Putting your shirt on backwards'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Eating dessert first'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Building a blanket fort'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Making a face'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Doing jumping jacks'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Singing loudly'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Running in slow motion'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Pretending you can''t hear'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Dramatic falling'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A spontaneous nap'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Asking "are we there yet?" repeatedly'),

-- Warning Signs / Red Flags
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'It sounds too good to be true'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'They''re asking for personal information'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'They want you to keep it a secret'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'It makes you feel uncomfortable'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'There''s lots of spelling errors'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'They''re pressuring you to decide quickly'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Something doesn''t feel right'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'They won''t give you time to think'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Your friends say it''s a bad idea'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Adults are saying no'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'It''s against the rules'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'You could get hurt'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Someone could get in trouble'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'It''s never worked before'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'They''re not who they say they are'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The website looks sketchy'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'They want money upfront'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'It''s probably illegal'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Your gut says no'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Something smells funny'),

-- Actions
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Stop and think'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Take three deep breaths'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Count to ten'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Walk away'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Find a quiet place'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Talk it out'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Write in a journal'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Draw a picture'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Listen to music'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Go for a walk'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Squeeze a stress ball'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Drink some water'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Have a healthy snack'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Take a power nap'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Stretch your muscles'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Get some fresh air'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Talk to someone you trust'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Ask for a hug'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Say "I need help"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Use your words'),

-- Time-Related
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Five more minutes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Tomorrow'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'When they''re finished talking'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Before it''s too late'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'At the right moment'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'After thinking it through'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Immediately'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'When asked'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'On time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Early'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Late, as usual'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'At the last minute'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Never'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Eventually'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Right now'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'In a little while'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'After lunch'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Before bedtime'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'First thing in the morning'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'When you''re ready'),

-- Common Phrases/Sayings
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"I don''t know"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"May I please..."'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"Thank you so much"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"I''m sorry, I made a mistake"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"Can you help me?"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"I need a minute"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"That''s not fair"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"I disagree"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"Good job!"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"You can do it!"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"I believe in you"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"Let me try again"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"I''ll do my best"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"What do you think?"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"I understand"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"That makes sense"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"I hadn''t thought of that"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"Great idea!"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"Tell me more"'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '"I''m proud of you"'),

-- Numbers/Specifics
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), '911'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Zero tolerance'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'One step at a time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Two heads are better than one'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Three strikes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Four corners of the room'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Five senses'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A second chance'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The first time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The last straw'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Number one priority'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Plan B'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Option C'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The final answer'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A hundred percent'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Half the time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Most of the time'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Always'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Sometimes'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Rarely'),

-- More silly/absurd answers for humor
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'My pet goldfish'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'An invisible friend'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A rubber duck'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Wearing a cape'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Superhero landing'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Jazz hands'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A victory dance'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A secret handshake'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Awkward silence'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Total chaos'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Organized chaos'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Somehow, success'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A standing ovation'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Confetti everywhere'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A dramatic pause'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'Plot twist!'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'The end credits'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A round of applause'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'A happy ending'),
((SELECT id FROM decks WHERE name = 'Cards Against Humanity - Life Skills Edition'), 'To be continued...');

-- Verify the card counts
SELECT 
  d.name as deck_name,
  (SELECT COUNT(*) FROM black_cards WHERE deck_id = d.id) as black_cards,
  (SELECT COUNT(*) FROM white_cards WHERE deck_id = d.id) as white_cards
FROM decks d
WHERE d.name = 'Cards Against Humanity - Life Skills Edition';
